matrix:
    include:
        - language: node_js
          dist: trusty
          sudo: required
          before_script:
              - cd Client/
              - npm install -g @angular/cli
          script:
              - ng lint
              - ng build

        - language: node_js
          before_script:
              - cd server/
