
matrix:
    include:
        - language: node_js
          node_js:
              - '8'
          dist: trusty
          cache:
              directories:
                  - 'node_modules'
          sudo: required
          before_script:
              - cd Client/
              - npm install -g @angular/cli
              - npm install
          script:
              - ng build

        - language: node_js
          node_js:
              - '8'
          cache:
              directories:
                  - "node_modules"
          before_script:
              - cd server/
              - npm install
          script:
              - npm run build
        - language: minimal
          sudo: required
          addons:
            sonarcloud:
              organization: "raphael-hascoet-github"
          before_script:
            - sudo add-apt-repository ppa:webupd8team/java -y
            - sudo apt update
            - sudo apt install oracle-java8-installer
          script:
            - sonar-scanner -X
